server.port=8080

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/exp9db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:exp9user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:exp9pass}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.sql.init.mode=never